### ISSUE TITLE
errors during backup/restore/upgrade on different server

### ISSUE THREAD

**Issue by knutole** [systemapic/docker-systemapic#16]
Doing a full run of backup/restore/upgrade on `tx`
#### Errors, notes:
1. Interrupt requested (ticket?)
2. `backup:postgis` image tries to do backup when starting (for some reason). fix. also - if trying to backup on start, the pgdb is not ready, resulting in fail.
3. backup goes to `/backup/postgis/` but not subdirectory (eg. timestamped). seems cleaner to have a separate folder for each backup (and keep only last, in case of error during latest backup).
#### Todo:
- [x]  fix interrupt requested bug
- [x] fix `backup:postgis` image so that it only dumps once per day
- [x] rename backup images to `systemapic/postgis:backup` - or create one backup image for all dbs (mongo, redis, postgis)?
- [x] backup into subdirectory
