### ISSUE TITLE
Docker Build Checklist

### ISSUE THREAD

**Issue by knutole** [systemapic/docker-systemapic#69]
- [ ] fix need to `npm install mapnik --build-from-source` manually (in `pile`)
- [ ] remove `apt-get` dependencies, as they're too flimsy to ensure stable build
- [ ] create build-proof fork of `mapnik` @ `systemapic/mapnik`
- [ ] add CI test to all builds 
- [ ] separate `wu` and `pile` deps (ie. `gis:latest`). no need to have mapnik in `wu`, no need for phantomjs in `pile`, etc. both should be leaner builds.
- [ ] remove postgres/postgis from `gis` build
- [ ] create much cleaner `gdal` build
