### ISSUE TITLE
getting localhost to work

### ISSUE THREAD

**Issue by knutole** [systemapic/docker-systemapic#70]
### Steps taken
- update package.json to latest

``` bash
npm install -g npm-check-updates
ncu -u
rm node_modules/ -r
npm install
```
- install `GLIBCXX_3.4.20` (due to `mapnik.node` error)  

``` bash
sudo apt-get install libstdc++6
# if that doesn't help:
sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y

```
- updated localhost config
### TODO
- [x] add this to pile/wu images
- [x] push to docker hub
- [ ] make tests work on `localhost`
